name: GitHub Actions AnxietyAlly
run-name: ${{ github.actor }} is merging branches
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building frontend has begun"
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "Building frontend has finished"
  jest-unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: echo "Testing frontend has begun"
    # - uses: actions/checkout@v4
    # - run: npm ci
    - run: npm run test
    - run: echo "Testing frontend has finished"
  eslint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      # - run: npm ci # or yarn install
      - uses: sibiraj-s/action-eslint@v3
        with:
          all-files: true
          # token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          ignore-path: .eslintignore
          extensions: 'js,jsx,ts,tsx'
          annotations: true
  deepsource-coverage:
    runs-on: ubuntu-latest
    env:
        DEEPSOURCE_DSN: https://cd414890ddd440b2b6d7d67d6517713e@app.deepsource.com
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    # Run your tests and generate coverage file here
    - name: Run Tests and Generate Coverage
      run: npm run coverage

    # Report test-coverage to DeepSource using CLI
    - name: Report test-coverage to DeepSource
      run: |
        # Install the CLI
        curl https://deepsource.io/cli | sh

        # Send the report to DeepSource
        ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml

  # trunk_check:
  #   name: Trunk Check Runner
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   permissions:
  #     checks: write # For trunk to post annotations
  #     contents: read # For repo checkout

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - run: npm install prettier-plugin-svelte

  #     - name: Trunk Check
  #       uses: trunk-io/trunk-action@v1