name: GitHub Actions AnxietyAlly
run-name: ${{ github.actor }} is pushing commit(s)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building frontend has begun"
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "Building frontend has finished"
  jest-unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: echo "Testing frontend has begun"
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test
    - run: npm run test-coverage
    - run: echo "Testing frontend has finished"
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1